# 13_condition_within_study.R
#
# The de-confounded estimate of each condition effect: every arrested sample is
# compared ONLY to Proliferating controls from its own study, and the per-study
# contrasts are combined with a stratified permutation test.
#
# WHY THIS IS THE RIGHT UNIT. Script 11 showed the controls are not
# exchangeable: study medians of untreated Proliferating cells span 87.8 tAge
# units on scaled_diff, which is larger than every condition effect. Script 12
# stratified by cell line, but cell line does not fix this, because a line is
# shared across studies (IMR90 appears in 15) while batch, protocol, passage,
# library prep and senescence-induction details are study-specific. Study is the
# finer and safer stratum: every study here contributes samples from a single cell
# line - VERIFIED per sample against each sample's own GEO characteristics in
# meta_analysis/14, not assumed - so a within-study contrast holds cell line,
# hTERT status, tissue and batch ALL constant by construction. In particular this
# removes the immortalisation confound of script 09 without dropping any samples.
#
# COVERAGE. 32 of 34 studies contain their own Proliferating controls, covering
# 223 of 230 samples, and all five conditions are testable. Only SRP096629 and
# SRP045867-type designs lacking internal controls are lost.
#
# THE TEST. Per study s with n_t arrested and n_c control samples, take
# d_s = mean(test) - mean(control). Combine as T = sum_s w_s d_s / sum_s w_s with
# w_s = n_t n_c / (n_t + n_c), the usual precision weight for a difference of
# means. The null is generated by permuting the condition label WITHIN each
# study, which preserves every study-level baseline exactly, so the p-value is
# free of the baseline heterogeneity that invalidates the pooled contrast. This
# is why small strata are usable: a 2-vs-2 study cannot reach significance
# alone (its minimum attainable p is 1/3) but it still contributes sign and
# magnitude information to T. RS exists only in such small strata, so it is
# ONLY testable this way.
#
# Reported alongside T: the number of studies with a positive difference and an
# exact binomial sign test, which is weaker but assumes nothing about magnitude.
#
# WHAT THIS DOES NOT FIX. Sampling of studies is still opportunistic, the
# senescence-induction protocol differs between studies within a condition, and
# tAge magnitudes remain uncalibrated (see TAGE_CALCULATION_AUDIT.md). This
# removes baseline confounding, not those.
#
# Output: rerun_outputs/condition_within_study.csv

source("R/config.R")
suppressPackageStartupMessages(library(dplyr))

set.seed(1)
NPERM <- 20000
MODELS <- c(scaled_diff = "scaled_diff_EN_tAge", yugene_diff = "yugene_diff_EN_tAge")

d <- read.csv(file.path(RERUN_DIR, "tage_all_conditions.csv"))
ann <- read.csv(file.path(RERUN_DIR, "immortalisation_annotation_corrected.csv"))
d$cell_line <- ann$cell_line_resolved[match(d$external_id, ann$external_id)]
d$immortalised <- ann$immortalised[match(d$external_id, ann$external_id)]
CONDS <- c("CICQ", "SSCQ", "RS", "SIPS", "OIS")

# The within-study design only controls cell line if each study really does use
# one. Checking that against cell_line_resolved would be circular, because script
# 10 ASSIGNS that column per study. Verify against the per-sample GEO evidence
# instead (meta_analysis/14), which reads each sample's own submitted
# characteristics. A GEO series can hold several lines - GSE106414 names
# BJ/ET/RasV12 and TIG3/ET/RASV12 in its methods - so this has to be checked, not
# assumed.
ver_path <- file.path(RERUN_DIR, "sample_level_line_verification.csv")
if (file.exists(ver_path)) {
  ver <- read.csv(ver_path)
  # pandas writes booleans as "True"/"False", which read.csv keeps as character
  ver$has_term <- toupper(as.character(ver$immortalisation_term_in_sample_record)) == "TRUE"
  chk <- ver %>% group_by(study) %>%
    summarise(n_lines = n_distinct(line_token_sample),
              n_imm = n_distinct(has_term),
              .groups = "drop")
  # a line token differing only by proliferating/quiescent wording is not a
  # different line; flag rather than fail, and report which studies
  if (any(chk$n_lines > 1 | chk$n_imm > 1)) {
    cat("NOTE: per-sample line/hTERT tokens vary within these studies -\n")
    print(as.data.frame(chk[chk$n_lines > 1 | chk$n_imm > 1, ]), row.names = FALSE)
    cat("  inspect sample_level_line_verification.csv before trusting their strata\n")
  }
  stopifnot(!any(ver$has_term != (ver$immortalised_studylevel == "yes")))
  cat(sprintf("per-sample GEO evidence agrees with the study-level call for all %d GEO samples\n",
              nrow(ver)))
} else {
  warning("sample_level_line_verification.csv missing; run meta_analysis/14 first")
}

strata_for <- function(cond, v) {
  s <- d[d$condition %in% c(cond, "Proliferating"), ]
  out <- lapply(split(s, s$study), function(g) {
    x <- g[[v]][g$condition == cond]; y <- g[[v]][g$condition == "Proliferating"]
    if (!length(x) || !length(y)) return(NULL)
    list(x = x, y = y, study = g$study[1], line = g$cell_line[1],
         imm = g$immortalised[1])
  })
  out[!vapply(out, is.null, logical(1))]
}

wstat <- function(st) {
  dd <- vapply(st, function(z) mean(z$x) - mean(z$y), numeric(1))
  w  <- vapply(st, function(z) length(z$x) * length(z$y) /
                               (length(z$x) + length(z$y)), numeric(1))
  sum(w * dd) / sum(w)
}

res <- list(); per_study <- list()
for (mn in names(MODELS)) {
  v <- MODELS[[mn]]
  for (cond in CONDS) {
    st <- strata_for(cond, v)
    obs <- wstat(st)
    # permute the condition label within each study
    perm <- replicate(NPERM, {
      wstat(lapply(st, function(z) {
        pool <- c(z$x, z$y); i <- sample.int(length(pool), length(z$x))
        list(x = pool[i], y = pool[-i])
      }))
    })
    p_perm <- (1 + sum(abs(perm) >= abs(obs))) / (NPERM + 1)
    dsl <- vapply(st, function(z) mean(z$x) - mean(z$y), numeric(1))
    npos <- sum(dsl > 0)
    res[[paste(mn, cond)]] <- data.frame(
      test = "condition_within_study_stratified", condition = cond, model = mn,
      n_studies = length(st),
      n_test = sum(vapply(st, function(z) length(z$x), integer(1))),
      n_control = sum(vapply(st, function(z) length(z$y), integer(1))),
      diff_within_study = obs,
      diff_pooled = median(d[[v]][d$condition == cond]) -
                    median(d[[v]][d$condition == "Proliferating"]),
      studies_positive = npos,
      p_sign = binom.test(npos, length(st), 0.5)$p.value,
      p_perm = p_perm)
    per_study[[paste(mn, cond)]] <- data.frame(
      test = "per_study_contrast", condition = cond, model = mn,
      study = vapply(st, function(z) z$study, character(1)),
      cell_line = vapply(st, function(z) z$line, character(1)),
      immortalised = vapply(st, function(z) z$imm, character(1)),
      n_test = vapply(st, function(z) length(z$x), integer(1)),
      n_control = vapply(st, function(z) length(z$y), integer(1)),
      diff = dsl, row.names = NULL)
  }
}
res <- bind_rows(res)
res$p_perm_adj <- ave(res$p_perm, res$model, FUN = function(x) p.adjust(x, "BH"))
per_study <- bind_rows(per_study)

for (mn in names(MODELS)) {
  cat(sprintf("\n===== %s : within-study stratified effect =====\n", mn))
  print(res[res$model == mn, c("condition", "n_studies", "n_test", "n_control",
                               "diff_within_study", "diff_pooled",
                               "studies_positive", "p_sign", "p_perm",
                               "p_perm_adj")],
        row.names = FALSE, digits = 3)
}

cat("\n\n===== per-study contrasts (the input to the above) =====\n")
for (cond in CONDS) {
  cat(sprintf("\n-- %s --\n", cond))
  s <- per_study[per_study$condition == cond, ]
  w <- merge(s[s$model == "scaled_diff", c("study", "cell_line", "immortalised",
                                           "n_test", "n_control", "diff")],
             s[s$model == "yugene_diff", c("study", "diff")],
             by = "study", suffixes = c("_scaled", "_yugene"))
  print(w, row.names = FALSE, digits = 3)
}

write.csv(bind_rows(res, per_study),
          file.path(RERUN_DIR, "condition_within_study.csv"), row.names = FALSE)
cat(sprintf("\nSaved -> %s\n", file.path(RERUN_DIR, "condition_within_study.csv")))
